[package]
name = "openvm-sha256-air"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
openvm-circuit-primitives = { workspace = true }
openvm-stark-backend = { workspace = true }
sha2 = { version = "0.10", features = ["compress"] }
rand.workspace = true
#openvm-native-compiler = { workspace = true }
#snark-verifier-sdk = { workspace = true, optional = true }
#once_cell = { workspace = true, optional = true, features = ["std"] }
#serde_with = { workspace = true, optional = true, features = ["hex"] }
openvm-native-recursion = { workspace = true, features = ["static-verifier", "evm-prove"] }
bincode = "1.3.3"
snark-verifier-sdk = {workspace = true}
[dev-dependencies]
openvm-stark-sdk = { workspace = true }
openvm-circuit = { workspace = true, features = ["test-utils"] }
[features]
default = ["parallel"]
parallel = ["openvm-stark-backend/parallel"]
#static-verifier = [
#    "openvm-native-compiler/halo2-compiler",
#    "snark-verifier-sdk",
#    "dep:once_cell",
#    "dep:serde_with",
#    "openvm-native-recursion/static-verifier"
#]