use serde::{Deserialize, Serialize};

/// Operations that can be constrained inside the circuit.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ConstraintOpcode {
    ImmV,
    ImmF,
    ImmE,
    AddV,
    AddF,
    AddE,
    AddEF,
    SubV,
    SubF,
    SubE,
    SubEF,
    MulV,
    MulF,
    MulE,
    MulEF,
    DivF,
    DivE,
    NegE,
    CastFV,
    AssertEqV,
    // AssertEqVI,
    AssertEqF,
    // AssertEqFI,
    AssertEqE,
    // AssertEqEI,
    CircuitPoseidon2Permute,
    Num2BitsV,
    CircuitNum2BitsF,
    CircuitVarTo64BitsF,
    CircuitSelectV,
    CircuitSelectF,
    CircuitSelectE,
    CircuitExt2Felt,
    PrintV,
    PrintF,
    PrintE,
    WitnessVar,
    WitnessFelt,
    WitnessExt,
    // CommitVkeyHash,
    // CommitCommittedValuesDigest,
    CircuitFelts2Ext,
    CircuitFeltReduce,
    CircuitExtReduce,
    CircuitLessThan,
}